[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  from = "/api/*"
  to = "https://d035-2601-646-401-2670-3deb-26d5-e74e-521.ngrok-free.app/api/:splat"
  status = 200